### PR TITLE
New temp support landing page

### PR DESCRIPTION
**Pull request by nimbinatus**
References:
id_support-page_doc
id_support-page_mockup-v1

### CODE REVIEW

**Comment by nimbinatus** [comment]
Note that the preview will not be accurate because the styles have not yet been merged to nexus-control (see rackerlabs/nexus-control#820).

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/support.rackspace.com/build-667eed6fa9/). :bow:

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-b6e3ffacb9/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/support.rackspace.com/build-43b20b2e7e/)

**Comment by robb-romans** [comment]
Approved by @ReneeRendon

**Comment by ReneeRendon** [comment]
Looks good.

**Pull request merged**
